### ISSUE TITLE
Naming metaclusters

### ISSUE THREAD

**Issue by PhillipSsekamatte** [lorenzobonaguro/cyCONDOR#12]
Hello Lorenzo

Thanks for the package. 
Is there a way to label phenotype and functional markers separately? But also perform additional clustering and dimensionality reduction on these markers separately, without the necessity to remove to use the remove_param argument upstream or marker_to_exclude when plotting the heatmap?

**Comment by PhillipSsekamatte** [comment]
Thanks Lorenzo, 
This helps.

**Comment by PhillipSsekamatte** [comment]
Hello Lorenzo, 
Is it possible that during generation of a "Heatmap for scaled expression", it is possible to specifiy the "expr_slot" to the specific markers of reduction and clustering other than simply having them excluded? For example, the default is "orig", but I had hoped I could specify my memory (pca_tcf_orig) and functional (pca_tcf_orig) markers

Code
plot_marker_HM(fcd = condor,
                   expr_slot = "orig",
                   cluster_slot = "FlowSOM_expr_orig_k_10",
                   cluster_var = "FlowSOM",
                   cluster_rows = T,
                   cluster_cols = F,
                   size = 15,
                   maxvalue = 2,
                   title = "Marker Expression Profile Across FlowSOM Clusters")

The same case goes for metaclustering and lebelling?

**Comment by lorenzobonaguro** [comment]
Hi Phillip,
Those are two separate things, you can use only specific markers for dimensionality reduction and clustering but this will not subset the markers in the expression slot, this is meant to give the user the option to still look at the expression of all measured markers.

If you want to exclude markers from the heatmap you can use the `marker_to_exclude` variable of the `plot_marker_HM` function. See detailed documentation [here](https://lorenzobonaguro.github.io/cyCONDOR/reference/plot_marker_HM.html).

If you want feel free to join our [Slack workspace](https://join.slack.com/t/cycondor/shared_invite/zt-2keb5ztaa-0aNKxP3OCglOTUiXDrtkhg), here we will probably be faster to answer you questions!

I hope this helps,
Lorenzo
