### ISSUE TITLE
Input on label transfer between cyTOF data and Spectral/Conventional flow data?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [lorenzobonaguro/cyCONDOR#16]
Hi there, 

Thanks again for the tool. 

The ability for label transfer is interesting. I wonder if it is appropriate and if so how to perform this prediction of CyTOF data onto flow cytometry data? Because the two might have been normalised differently and having different markers in the panel. 

https://lorenzobonaguro.github.io/cyCONDOR/articles/Data_Projection.html

Thank you for your help.

**Comment by lorenzobonaguro** [comment]
Hi @denvercal1234GitHub , as you anticipated data projection do not work really well with data from different technologies, we implemented this workflow more with the idea of having a quick approach to transfer label to new data generated with the same technology/panel. We have a couple of ideas on how to transfer informations from one technology to another using `Astir` but this is still currently experimental. Btw I see you really active in here, maybe consider joining our [Slack Workspace](https://join.slack.com/t/cycondor/shared_invite/zt-2keb5ztaa-0aNKxP3OCglOTUiXDrtkhg)

**Comment by denvercal1234GitHub** [comment]
Thanks Lorenzo. I would love to, but Slack is just so overwhelming. lol. Will consider it though. Thanks again for all your help and for developing the tool. Looking forward to seeing the Astir implementation.
