### ISSUE TITLE
Typo in guideline for `runUMAP` for harmony batch correction workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [lorenzobonaguro/cyCONDOR#4]
Hi there, 

Thanks for the tool. 

In the tutorial (https://lorenzobonaguro.github.io/cyCONDOR/articles/Batch_correction.html), it mentioned "Repeat dimensionality reduction: With the corrected PC coordinates we can not run again the UMAP function." Is this a typo? 

Also would you mind giving me some guideline or resources to determine when to batch correct directly on fluorescence intensity vs on PCs?

Thank you!

```
condor <- runUMAP(fcd = condor, 
                  input_type = "pca", 
                  data_slot = "norm", 
                  seed = 91)
```

**Comment by lorenzobonaguro** [comment]
Hey,
Yes indeed there is a small typo, the sentence should read: "Repeat dimensionality reduction: With the corrected PC coordinates we can **now** run again the UMAP function."

We are currently working on a more extended tutorial for the next release, should be there in few weeks.

For a more detailed guideline on the use of intensities or PCs for batch correction you can have a look at our pre-print:
https://www.biorxiv.org/content/10.1101/2024.02.29.582727v1
