### ISSUE TITLE
Input regarding how to select specific set of markers for clustering?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [lorenzobonaguro/cyCONDOR#5]
Hi there, 

I was wonder whether it would be possible to specify certain markers to be used for clustering instead of clustering the cells by all available markers?

Thanks for the package and for your help!

**Comment by lorenzobonaguro** [comment]
Hey,
You are right, currently you would need to exclude the markers from the `prep_fcd` function (`remove_param` argument).

We are implementing the possibility to select the parameters specifically for dim reduction and clustering with the new version of `cyCONDOR` expected in few weeks.

I will provide you with a temporary solution in 1-2 days, give me the time to get back to the team!

Thanks for the feedbacks.

**Comment by lorenzobonaguro** [comment]
Hey @denvercal1234GitHub sorry for taking longer than expected, we are currently working on a major update of the package which should be ready in few days, including the feature your requested, please hold on. Will drop you a message asap!

**Comment by denvercal1234GitHub** [comment]
Thank you @lorenzobonaguro -- In addition to the above (and interchanging between cyCONDOR and single cell experiment object), it would be very useful to have more QC functions to check the data (e.g., whether the cells were transformed properly etc) before the dimensionality steps and especially before clustering. In addition, functions such as non-redundancy score ranking for markers to find markers most explain variance of the sample (to assist with picking markers for clustering) and function to assess cluster resolution parameter to choose for clustering (k, meta) would be particularly useful.

**Comment by lorenzobonaguro** [comment]
Hi @denvercal1234GitHub as the main question of this issue is was now addressed in `v0.2.0` I would close it. Feel free to open a new one with suggestions for further improvement, we are happy to have your feedbacks!

Lorenzo
